### ISSUE TITLE
Simple way to contact the NHSBSA

### ISSUE THREAD

**Issue by nhsbsa-mawil** [nhsbsa-data-analytics/open-data-roadmap#17]
# Summary
A known pain point for users is the lack of a clear channel to communicate issues or queries back to the NHSBSA. 

# Intended outcome
A clear channel will be created, and communicated, to make it simpler for users to feedback. This will also include being informed of the outcome.

# How will it work?
Within NHSBSA a new Customer Relationship Management system has been created to manage the customer journey. This has included standardising email addresses that are used to gain feedback. It has also involved standardising the process for responding to queries.

**Comment by MWilson92** [comment]
We have now implemented a new Customer Relationship Management (CRM) system.

This enables us to get a full picture of how our customers interact with us, help us continue to provide good customer service and make sure our Service Level Agreements (SLAs) are being met.

The new system brings several improvements and benefits. 
* Updating our email contact addresses to make it easier for our customers to know which service they are contacting, which will lead to improved response times.
* Identify training requirements 
* Identify where system improvements can be made
* Ensure we get a full picture of how our customers interact with us

As part of the implementation, we have had to change some of our email addresses:

### Prescribing
* **ePACT2support@nhsbsa.nhs.uk**
Exclusively for ePACT2 queries and ePACT2 training queries, previously received via nhsbsa.help@nhs.net, nhsbsa.informationsystems@nhs.net and nhsbsa.epact2training@nhs.net.
* **registration@nhsbsa.nhs.uk**
To register for our systems replacing nhsbsa.registration@nhs.net.
* **dataandinsightsupport@nhsbsa.nhs.uk**
Replaces nhsbsa.help@nhs.net and nhsbsa.informationsystems@nhs.net for all Data and Insight enquiries not relating to ePACT2.
* **datarequest@nhsbsa.nhs.uk**
For those users who need to request data that is not readily available and for those authorised to request patient NHS numbers, replaces nhsbsa.datarequest@nhs.net. **Only available to NHS and public sector workers**.

### Ophthalmic
* **eOPSsupport@nhsbsa.nhs.uk**
Exclusively for eOPS queries including registration, password resets and training queries previously received via nhsbsa.dentalinsight@nhs.net.
* **ophthalmicinsight@nhsbsa.nhs.uk**
Replaces nhsbsa.ophthalmicinsight@nhs.net for all other queries including data requests.

### Dental
* **eDENsupport@nhsbsa.nhs.uk**
Exclusively for eDEN queries including registration, password resets and training queries previously received via nhsbsa.dentalinsight@nhs.net.
* **dentalinsight@nhsbsa.nhs.uk**
Replaces nhsbsa.dentalinsight@nhs.net for all other queries including data requests.
